apiVersion: v1
kind: Service
metadata:
  name: #{Template.Service.Name}
  labels:
    component: #{Template.Labels.Component}
spec:
  type: ClusterIP
  selector:
    component: #{Template.Labels.Component}
  ports:
    - port: #{Template.Service.Port}
      targetPort: #{Template.Service.TargetPort}
      name: #{Template.Service.PortName}
