apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Template.Deployment.Name}-canary
spec:
  replicas: 0
  selector:
    matchLabels:
      component: #{Template.Labels.Component}
      type: canary
  template:
    metadata:
      labels:
        component: #{Template.Labels.Component}
        type: canary
    spec:
      containers:
        - name: #{Template.Labels.Component}
          image: #{Octopus.Action.Package[app-container].Image}
          ports:
            - containerPort: #{Template.Service.Port}
              name: #{Template.Service.PortName}
