apiVersion: v1
kind: Service
metadata:
  name: #{Project.Service.Name}
  labels:
    component: #{Project.Labels.Component}
    type: main
spec:
  type: ClusterIP
  selector:
    component: #{Project.Labels.Component}
  ports:
    - port: #{Project.Service.Port}
      targetPort: #{Project.Service.TargetPort}
      name: #{Project.Service.PortName}
