apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Template.Deployment.Name}
spec:
  replicas: #{Template.Deployment.Replicas}
  selector:
    matchLabels:
      component: #{Template.Labels.Component}
      type: main
  template:
    metadata:
      labels:
        component: #{Template.Labels.Component}
        type: main
    spec:
      containers:
        - name: #{Template.Labels.Component}
          image: #{Octopus.Action.Package[app-container].Image}
          ports:
            - containerPort: #{Template.Service.Port}
              name: #{Template.Service.PortName}
