name: Multispace - Apply Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/multispace-apply.yml
      - terraform/multispace/**
      - terraform/modules/**
  workflow_dispatch:

jobs:
  call-apply-terraform:
    uses: ./.github/workflows/terraform-apply.yml
    secrets: inherit
    with:
      terraform-folder: multispace
      state-key-secret-name: "TFSTATE_KEY"
      octopus-apikey-secret-name: "OCTOPUS_APIKEY"
    permissions:
      id-token: write
      contents: read
