name: Team B - Apply Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/team-b-apply.yml
      - terraform/team-b/**
      - terraform/modules/**
  workflow_dispatch:

jobs:
  call-apply-terraform:
    uses: ./.github/workflows/terraform-apply.yml
    secrets: inherit
    with:
      terraform-folder: team-b
      state-key-secret-name: "TEAM_B_STATEKEY"
      octopus-apikey-secret-name: "TEAM_B_APIKEY"
    permissions:
      id-token: write
      contents: read
