name: Team B - Destroy Terraform

on:
  workflow_dispatch:

jobs:
  call-apply-terraform:
    uses: ./.github/workflows/terraform-destroy.yml
    secrets: inherit
    with:
      terraform-folder: team-b
      state-key-secret-name: "TEAM_B_STATEKEY"
      octopus-apikey-secret-name: "TEAM_B_APIKEY"
    permissions:
      id-token: write
      contents: read
